version: "3"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: express_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  jenkins:
    build: ./cicd/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

volumes:
  jenkins_home: